#This script does some basic checking on your files to see if you are missing anything obvious
#...such as uploading code that does not compile or is missing a file mentioned in the lab sheet.
#
#Successful run of the pipeline is not a guarantee the behaviour of the code is correct.
stages:
  - build
  - test #No tests this week

image: maven:latest


compile:
  stage: build
  script:
    - mvn compile
    - mvn test-compile

name-check:
  stage: test
  script:
    - if ! [ -f "src/main/java/Snap.java" ]; then exit 1; fi 
    - if ! [ -f "src/main/java/Sevens.java" ]; then exit 1; fi 

